name: mercuryhealth-web-ci-pr

on:
  pull_request:
    branches: [ none ]

  # allow this to be run from the Actions view
  workflow_dispatch:
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - run: git checkout HEAD^2
      if: ${{ github.event_name == 'pull_request' }}
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: javascript, csharp

    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1
